# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='phone',
        ),
    ]
