# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_auto_20190224_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='gender',
            field=models.CharField(default='m', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
